### ISSUE TITLE
Dumping roms problem 

### ISSUE THREAD

**Issue by haps-basset** [Ebiroll/qemu_esp32#28]
Hello 
I’ve followed your instruction and I got a problem with dumping roms from my ESP32. It is a copy of  ESP32 devkit doit. Any attempt to dump roms failed giving me the following shown below.
Could you advise what is wrong?  ESP32 is a new soc for me, therefore, any advice in this matter highly appreciated.
haps

esptool.py --chip esp32 -b 921600 -p com3: dump_mem 0x40000000 0x000C2000 rom.bin
esptool.py v3.0
Serial port com3:
Connecting.....
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 24:6f:28:aa:8e:c4
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
794624 bytes read... (100 %)Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python39\Scripts\esptool.py-script.py", line 33, in <module>
    sys.exit(load_entry_point('esptool==3.0', 'console_scripts', 'esptool.py')())
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python39\site-packages\esptool.py", line 3962, in _main
    main()
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\esptool.py", line 3604, in main
    operation_func(esp, args)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\esptool.py", line 2840, in dump_mem
    print_overwrite("Read %d bytes" % f.tell(), last_line=True)
ValueError: I/O operation on closed file

esptool.py --chip esp32 -b 921600 -p com3: dump_mem 0x3FF90000 0x00010000 rom1.bin
esptool.py v3.0
Serial port com3:
Connecting....
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 24:6f:28:aa:8e:c4
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
65536 bytes read... (100 %)Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\Scripts\esptool.py-script.py", line 33, in <module>
    sys.exit(load_entry_point('esptool==3.0', 'console_scripts', 'esptool.py')())
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\esptool.py", line 3962, in _main
    main()
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\esptool.py", line 3604, in main
    operation_func(esp, args)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\esptool.py", line 2840, in dump_mem
    print_overwrite("Read %d bytes" % f.tell(), last_line=True)
ValueError: I/O operation on closed file

**Comment by nx518** [comment]
I got the same error message.
However the dumps still seem to be generated correctly.
This issue is more related to https://github.com/espressif/esptool than qemu.
